### ISSUE TITLE
Special Case - Fortigate long SSH login issues

### ISSUE THREAD

**Issue by KodySalak** [rconfig/rconfig#177]
Fortigate OS version  7.2.11 and a few others are having long SSH login issues due to the way they are handling SSH login on the device end. It is noted [here](https://community.fortinet.com/t5/FortiGate/Troubleshooting-Tip-SSH-admin-sessions-slow-login/ta-p/393996) that they are releasing updates to fix this issue, but not for the 7.2.11 train of software, which is what my Fortigate (100E) is getting as it's last update. Is there a way that I myself or you to add a delay before sending the "grab config" commands for the fortigate? 

I tried adding a sleep(20); in Login.php at /var/www/html/rconfig/app/Http/Controllers/Connections/SSH on lines 28, 57, 60, 67, 72, 77, and 86 - all with no change in the error I receive:
```
Start rconfig:download-device IDs:4
Start device download for ROUTER ID:4
No config data returned for ROUTER - ID:4. Check your logs for more information
End rconfig:download-device
```

Any help on where I could put a sleep for it to just take a coffee break before it asks for the config is all I'm asking for :)

Thanks!

**Comment by stephenstack** [comment]
Apologies for delayed response. Did you get this resolved?

**Comment by KodySalak** [comment]
I have not.

**Comment by rconfig** [comment]
ok, firstly check the logs in the UI for any auth or connections errors. Then check the Queue Manager for an job failures. Lets go back to basics for a minute before we start to introduce sleeps in to code. Which i'm not against, but the No config data returned for ROUTER - ID:4. Check your logs for more information error usually means an auth error or connection error. And may its this part that requires the 'sleep'

**Comment by KodySalak** [comment]
### "Main" Logs in UI

First Error:
```
{
  "id": 22978,
  "log_name": "error",
  "description": "Authentication Failed for 10.0.10.1 ID:4. Or wrong prompt configured for this device! Check your device settings.",
  "subject_id": null,
  "subject_type": null,
  "causer_id": null,
  "causer_type": null,
  "properties": [],
  "batch_uuid": null,
  "event_type": "connection",
  "device_name": "10.0.10.1",
  "device_id": "4",
  "events_ids": null,
  "connection_category": "device",
  "connection_ids": "N;",
  "class": "App\\Http\\Controllers\\Connections\\SSH\\Login",
  "function": "loginErrorCheck",
  "created_at": "2025-07-31T07:30:44.000000Z",
  "updated_at": "2025-07-31T07:30:44.000000Z"
}
```

Second Error:
```
{
  "id": 22979,
  "log_name": "error",
  "description": "There was an authentication or connection issue with ROUTER",
  "subject_id": null,
  "subject_type": null,
  "causer_id": null,
  "causer_type": null,
  "properties": [],
  "batch_uuid": null,
  "event_type": "connection",
  "device_name": "10.0.10.1",
  "device_id": "4",
  "events_ids": null,
  "connection_category": "device",
  "connection_ids": "N;",
  "class": "App\\Http\\Controllers\\Connections\\SSHConnectionManager",
  "function": "SSHConnectionAndOutput",
  "created_at": "2025-07-31T07:30:44.000000Z",
  "updated_at": "2025-07-31T07:30:44.000000Z"
}
```

### Job Queues:
There are no failed jobs in the queue section of rConfig.

The same user/password lets me sign into the fortigate and also lets me run the `show full-configuration` command, which is what is running when rConfig does it's thing... but it still takes 15+ seconds to log in, and I don't think rConfig is waiting for it.

**Comment by rconfig** [comment]
ok, so if you go to the device page, and click the Copy Debug button, the go to the CLI and paste in the command. What output do you get. Make sure to sanitize it before posting here. 

The logs seem clear this is an auth or connection issue. i would also try basic SSH from the rConfig Server CLI to the device and verify creds and connectivity.

**Comment by KodySalak** [comment]
```
root@rconfig:/var/www/html# cd /var/www/html/rconfig && php artisan rconfig:download-device 4 -d
Start rconfig:download-device IDs:4
Start device download for ROUTER ID:4
No config data returned for ROUTER - ID:4. Check your logs for more information
End rconfig:download-device
root@rconfig:/var/www/html/rconfig#
```

for the below test, I copy/pasted the user/password straight from rConfig's UI. 

```
root@rconfig:/var/www/html/rconfig# ssh admin@10.0.10.1
##### 9 seconds of "nothing/loading" from the fortigate
admin@10.0.10.1's password:
##### 10 seconds of the same "nothing/loading" from the fortigate
router #
```

As I have said before (and I do appreciate the thoroughness), this is a fortigate problem, and rConfig just needs to wait for it to log in.

**Comment by KodySalak** [comment]
Finally fixed! After taking a step back and looking through the UI, I found that there is a `timeout` in the fortigate-ssh-noenable.yml template. 

fortigate-ssh-noenable.yml:
```
# rConfig connection template - DO NOT EDIT DIRECTLY
## Notes: 
    ## Remember to update permissions for the templates folder after uploading new template files.
    ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "Fortigate SSH no enable"
  desc: "Fortigate SSH no enable"
connect:
  # connection timeout in seconds
  timeout: 30 ### <------ THIS IS WHAT WAS CHANGED
  # type either telnet or ssh - must be in lowercase
  protocol: ssh
...
```
Line 13 is what I changed, from 5 to 20 seconds.
