### ISSUE TITLE
3.8 beta - massive notices and warnings when running task on cli

### ISSUE THREAD

**Issue by mcramer85** [rconfig/rconfig#46]
When I run a task on the cli (eg php /home/rconfig/lib/showCmdScript.php 986528) I get massive notices and warnings, even if error logging for php is turned off:

```
PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396
PHP Warning:  implode(): Invalid arguments passed in /home/rconfig/lib/showCmdScript.php on line 233
```

This makes it nearly impossible to debug the connection to a device.

**Comment by rconfig** [comment]
updated tags, investigating

**Comment by rconfig** [comment]
please PM on private slack. Will need to see device details and full output. Please add 'true' keyword after the command, and send me the details. ensuring no passwords are sent etc...

**Comment by rconfig** [comment]
I am unable to replicate this. Please let me know;
1. device make/ model/ code rev you are trying to connect to
2. post the connection template file here
3. Go to settings page, enable 'Device debugging Output' and run the showCmdScript.php, with the 'true' keyword/ parameter after the taskID i.e. showCmdScript.php 123456 true

Post the output here. 

thanks

**Comment by mcramer85** [comment]
1. HPE/Aruba 2530-48G J9775A Firmware #YA.16.02.0012
2. 
```
# rConfig connection template - DO NOT EDIT DIRECTLY
## Notes: 
    ## Remember to update permissions for the templates folder after uploading new template files.
    ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "HPE ArubaOS - SSH - No Enable"
  desc: "HPE ArubaOS SSH based connection without enable mode"
connect:
  # connection timeout in seconds
  timeout: 60
  # type either telnet or ssh - must be in lowercase
  protocol: ssh
  # type port number for connection protocol choose from 1 - 65535
  port: 22
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: "Username:"
  # Set password name prompt. Must be in quotes
  password: "Password:"
  # Set enable mode on or off
  enable: off
  # set enable mode command. Must be in quotes
  enableCmd: "enable"
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: "Password:"
config:
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: "no page"
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: "page"
    # Set pager prompt. Must place command in quotations
    pagerPrompt: "-- MORE --"
    # Set pager prompt key-stroke. Must place command in quotations
    pagerPromptCmd: " "
    # Save configuration command. Leave blank, or set as required. Must be in quotes
    saveConfig: "wr mem"
    # Set exit command. Must place command in quotations
    exitCmd: "quit"
```
