### ISSUE TITLE
Unable to get a full config backup

### ISSUE THREAD

**Issue by 6r1zzlyB** [rconfig/rconfig#49]
Having an issue getting a full config backup from an Aruba 2930F. I can get some output, but it is cutoff. If I enable AnsiHost, it gets better, but still not 100%.

In some cases, it looks like the config will span more than one output file.

Config with ANSI
![config_with_ansi](https://github.com/rconfig/rconfig/assets/8052316/d744b73e-e566-48e0-a77a-99f68678c635)

Config without ANSI
![config_without_ansi](https://github.com/rconfig/rconfig/assets/8052316/aab7cd5d-d5d0-40c4-9358-ddfb9223a5db)

Version with ANSI
![version_with_ansi](https://github.com/rconfig/rconfig/assets/8052316/cd85affb-3830-4111-99a1-faadedda74d7)

Version without ANSI
![version_without_ansi](https://github.com/rconfig/rconfig/assets/8052316/b1145114-88ba-4dfe-9384-f87a0324ae6d)

Here is the template used.
```
main:
  name: ArubaOS 2930F
  desc: ArubaOS 2930F
connect:
  timeout: 10
  protocol: ssh
  port: 22
auth:
  username: "Username:"
  password: "Password:"
  enable: off
  enableCmd: "enable"
  enablePassPrmpt: "Password:"
  hpAnyKeyStatus: on
  hpAnyKeyPrmpt: "Press any key to continue"
config:
  linebreak: "n"
  paging: on
  pagingCmd: "no page"
  resetPagingCmd: "page"
  pagerPrompt: "-- MORE --, next page: Space, next line: Enter, quit: Control-C"
  pagerPromptCmd: " "
  saveConfig: "save"
  exitCmd: "quit"
#options:
#  AnsiHost: "yes"
```
