### ISSUE TITLE
3.8beta - Fatal error: Uncaught Error: Call to undefined method Connection::write() in /home/rconfig/classes/connection2.class.php

### ISSUE THREAD

**Issue by jdcraymond** [rconfig/rconfig#49]
After the workaround for issue #48, there was a fatal error running showCmdScript.php

Fatal error: Uncaught Error: Call to undefined method Connection::write() in /home/rconfig/classes/connection2.class.php:285

I believe line 285 and 287 need to be changed from $this->write and $this->read to $ssh->write and $ssh->read respectively.

After changing those lines, showCmdScript.php hung until I removed line 289. 

Once I mad the changes to line 285, 287 and 289 I was able to run showCmdScript.php successfully.

**Comment by rconfig** [comment]
will have to get more information on this one. Can you post your template for the connection that fails? Can you also enable 'Debug device output:' on the settings page. 
Then run the showCmdScript.php with the true keyword set, and lets see where it failes or hangs. 

Thanks

**Comment by jdcraymond** [comment]
I'm using the Cisco IOS - SSH - No Enable Profile that comes with it:

```
# rConfig connection template - DO NOT EDIT DIRECTLY
## Notes: 
    ## Remember to update permissions for the templates folder after uploading new template files.
    ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "Cisco IOS - SSH - No Enable"
  desc: "Cisco IOS SSH based connection without enable mode"
connect:
  # connection timeout in seconds
  timeout: 60
  # type either telnet or ssh - must be in lowercase
  protocol: ssh
  # type port number for connection protocol choose from 1 - 65535
  port: 22
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: "Username:"
  # Set password name prompt. Must be in quotes
  password: "Password:"
  # Set enable mode on or off
  enable: off
  # set enable mode command. Must be in quotes
  enableCmd: "enable"
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: "Password:"
config:
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: "terminal length 0"
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: "terminal length 40"
    # Set pager prompt. Must place command in quotations
    pagerPrompt: "--More--"
    # Set pager prompt key-stroke. Must place command in quotations
    pagerPromptCmd: " "
    # Save configuration command. Leave blank, or set as required. Must be in quotes
    saveConfig: "wr mem"
    # Set exit command. Must place command in quotations
    exitCmd: "quit"
```
The output final part of the output is

Notice: ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396

Fatal error: Uncaught Error: Call to undefined method Connection::write() in /home/rconfig/classes/connection2.class.php:285
Stack trace:
#0 /home/rconfig/lib/showCmdScript.php(208): Connection->connectSSH('show startup-co...', 'switch1#', '1')
#1 {main}
  thrown in /home/rconfig/classes/connection2.class.php on line 285
